sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IcA8IZ/5EH8S0DK48UbFhz1fCWykmE+jBktMa6lYvsjfxfi/ejJn3LMye3ltzxK6J3h7Zi9nhBUdU/K+gCo7AZUOwivxDV4/Zxx5qQXPg8HW+2AZasLnxvPkNfZksq9Z6IjsHUDgagZ9s2OUZ4n30zGgDnYiY/QzuDJfKO/ak0J3ly0cmJhQescUd06R3If4jnkWMr4KRHvJ++LmSgptBowT/0IHmpK9798SKmaVhJKpCAyFDtFWl48rX8VtX6v9eRXIaetwhjINV1EP1kIeCnrf92SOELT61tTAszofUO7hG6NVJS0Qpyv+zDiJmJS86SMUuwa3pb198L8xpZe+eDyn5TWU8xu8Kf6zdvxoUMAtDvKs48Q5k0HfKLkobQvMMQu5ERfZg/GiqHPT7jFeKXdR8elWLWKUXus/AW4MHwEmAXAHqGMM+6dyk7H+yP/iRBmGDDNE29Qc/RcNSvEfDpHgBQm2jFZj3yJmesV7jaxAoU00qff18gmAxOkVBwLzbK4//E7zm4prxJ0oUxFV+kvVUaPzsfhOyu1Kt+OZclFgsR98q1IspOA3IuO7DadpCq+8UEOux2wlF4B0YBc1BP9Yh5xrrwgFc7sf5KssWAMi9vDDQjfn11xVtGGKeaYDPvg0sLVcxihhk9RTJl8vJMvBGIDs6P1HSqPXjbI4/H0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Artemis-to-Actaeon-and-Other-Verses_4549
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy